// https://tools.ietf.org/html/rfc4861#section-4.6.1
// "Source/Target" Link-layer Address hereby shortened to LinkLayerAddress
typedef u128 LinkLayerAddress;

dictionary LinkLayerAddressType {
	u8 Source = 1;
	u8 Target = 2;
};

interface SourceLinkLayerAddress : LinkLayerAddress {
	const byte Type = 2;
};
interface TargetLinkLayerAddress : LinkLayerAddress {
	const byte Type = 3;
};
