// https://tools.ietf.org/html/rfc4861#section-4.4
interface NeighborAdvertisement : Icmp {
	const byte IpHopLimit = 255;
	attribute byte icmpType = 136;
	attribute byte icmpCode = 0;

	[Alias=R,BitStart=0,BitMasks=reserved]
	attribute bool router;
	[Alias=S,BitStart=1,BitMasks=Reserved]
	attribute bool solicited;
	[Alias=O,BitStart=2,BitMasks=Reserved]
	attribute bool override;
	attribute u32 reserved;
	attribute LinkLayerAddress targetAddress;
	attribute LinkLayerAddress? targetLinkLayerAddress;
};
