// https://tools.ietf.org/html/rfc4861#section-4.3
interface NeighborSolicitation : Icmp {
	const IcmpType = 135;
	const IcmpCode = 0;
	attributes unsigned long reserved;
	attributes long long targetAddressTop;
	attributes long long targetAddressBottom;
	attributes LinkLayerAddress? sourceLinkLayerAddress;
}
