// https://tools.ietf.org/html/rfc4861#section-4.4
interface NeighborAdvertisement : Icmp {
	const IcmpType = 136;
	const IcmpCode = 0;
	attributes bool router;
	attributes bool solicited;
	attributes bool override;
	attributes long reserved;
	attributes LinkLayerAddress targetAddress;
	attributes LinkLayerAddress? targetLinkLayerAddress;
}
