// https://tools.ietf.org/html/rfc4861#section-4.6
// [ed: i expect this more or less works like ip-ext/option but has types? this is an "extension" idl"]
interface Option {
	[Values="OptionType"]
	attribute byte optionType;
	attribute byte optionLength;
};

dictionary OptionType {
	byte SourceLinkLayerAddress = 1;
	byte TargetLinkLayerAddress = 2;
	byte PrefixInformation = 3;
	byte RedirectedHeader = 4;
	byte MTU = 5;
};
