// https://tools.ietf.org/html/rfc4861#section-4.5
interface Redirect : Icmp {
	const IcmpType = 137;
	const IcmpCode = 0;
	attributes long reserved;
	attributes long long targetAddressTop;
	attributes long long targetAddressBottom;
	attributes long long destinationAddressTop;
	attributes long long destinationAddressBottom;
	attributes LinkLayerAddress? targetLinkLayerAddress;
	attributes IpHeader redirectHeader;
}
